Add a stub for the quarterly update
input-output-hk/cardano-updates pull request #194
Opened 2023-06-28 12:20 UTC by dnadales

2023-07-04 09:38 UTC, amesgen approved these changes

2023-07-04 13:17 UTC, disassembler approved these changes

2023-07-06 07:31 UTC, coot requested changes
Please rename the file to `quarterly/2023-06-06-consensus.md` or `quarterly/2023-q2-consensus.md`.

2023-07-06 21:02 UTC, coot commented on quarterly/Q3-consensus.md
> +## Consensus Quarterly Update
```suggestion
```
The title is already set by `title:` above

2023-07-06 21:07 UTC, coot commented on quarterly/Q3-consensus.md
> +title: Consensus Quarterly Update
I think we should use something like: `Consensus Q2 2023 Update`, otherwise they are indistinguishable in the left pane which list multiple entries.

2023-07-13 23:58 UTC, disassembler commented on quarterly/Q3-consensus.md
> +title: Consensus Quarterly Update
```suggestion
title: Consensus Q2 2023 Update
```

2023-07-14 06:57 UTC, coot approved these changes

2023-07-16 17:45 UTC, merged